name: Docker User

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    container: pisanuw/csslab

    steps:
    
    - uses: actions/checkout@v2

    - name: Run docker-user.sh file
      run: ./docker-user.sh
